name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      uses: shirhatti/dotnet-buildexecutable-action@master
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - name: Upload artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: '/Release/netcoreapp3.0/**/publish/*'
