name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      uses: shirhatti/dotnet-buildexecutable-action@master
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - name: List artifacts
      run: ls src/LogViewer/
    
